(print "Starting Concurrency Test")
(let ((pid (mp:spawn #'(lambda () 
                    (print "Background Task Started")
                    (sleep 500)
                    (print "Background Task Finished")))))
  (print "Foreground Task Continuing")
  (print pid)
  (sleep 1000)
  (print "Foreground Task Finished"))
(print "Step 2")
(sleep 1000)
