(format t "Starting MOP Class Creation Protocol Test...~%")

(defclass base ()
  ((a :initarg :a)
   (b :initarg :b))
  (:default-initargs :a 1 :b 2))

(let ((obj (make-instance 'base)))
  (if (= (slot-value obj 'a) 1)
      (format t "DEFAULT-INITARGS a OK~%")
      (format t "DEFAULT-INITARGS a FAIL~%"))
  (if (= (slot-value obj 'b) 2)
      (format t "DEFAULT-INITARGS b OK~%")
      (format t "DEFAULT-INITARGS b FAIL~%")))

(let ((obj (make-instance 'base :a 10)))
  (reinitialize-instance obj :b 20)
  (if (= (slot-value obj 'a) 10)
      (format t "REINITIALIZE-INSTANCE preserves a OK~%")
      (format t "REINITIALIZE-INSTANCE preserves a FAIL~%"))
  (if (= (slot-value obj 'b) 20)
      (format t "REINITIALIZE-INSTANCE sets b OK~%")
      (format t "REINITIALIZE-INSTANCE sets b FAIL~%")))

(let ((class (find-class 'base)))
  (let ((plist (class-default-initargs class)))
    (if (and plist (eq (car plist) :a) (= (cadr plist) 1)
             (eq (caddr plist) :b) (= (cadddr plist) 2))
        (format t "CLASS-DEFAULT-INITARGS OK~%")
        (format t "CLASS-DEFAULT-INITARGS FAIL~%")))
  (let ((plist (slot-value class 'direct-default-initargs)))
    (if (and plist (eq (car plist) :a) (= (cadr plist) 1))
        (format t "CLASS metaobject DIRECT-DEFAULT-INITARGS slot OK~%")
        (format t "CLASS metaobject DIRECT-DEFAULT-INITARGS slot FAIL~%"))))

(defclass c1 ()
  ((x :initarg :x)
   (y :initarg :y)))

(defclass c2 ()
  ((y :initarg :y)
   (z :initarg :z)
   (w :initform 42)))

(let ((obj (make-instance 'c1 :x 1 :y 2)))
  (change-class obj 'c2 :z 3)
  (if (= (slot-value obj 'y) 2)
      (format t "CHANGE-CLASS preserves y OK~%")
      (format t "CHANGE-CLASS preserves y FAIL~%"))
  (if (= (slot-value obj 'z) 3)
      (format t "CHANGE-CLASS sets z OK~%")
      (format t "CHANGE-CLASS sets z FAIL~%"))
  (if (= (slot-value obj 'w) 42)
      (format t "CHANGE-CLASS initform w OK~%")
      (format t "CHANGE-CLASS initform w FAIL~%")))

(if (validate-superclass (find-class 'standard-class) (find-class 'standard-object))
    (format t "VALIDATE-SUPERCLASS OK~%")
    (format t "VALIDATE-SUPERCLASS FAIL~%"))
