(defmacro my-incf (place)
  (let ((val 1))
    `(setf ,place (+ ,place ,val))))

(let ((x 1))
  (my-incf x)
  (if (= x 2)
      (print "Incf works")
      (error "Incf failed")))

(let ((res nil))
  (push 1 res)
  (if (equal res '(1))
       (print "Push works")
       (error "Push failed")))
